INSERT INTO TBLSYSFUNCTION(FUNCTIONNO,FUNCTIONNAME,FUNCTIONORDER,MODULENO,FORMNAME,WEBURL,CREATOR,CREATEDATE,PRIVOPTION,ISSUEOPTION,ISSUETABLE,EXECUTIONFILE,FUNCTIONKEY,ExecutionMode,H5FUNCTIONKEY)
VALUES ('PRS POSITION BASIS','工位流程基本资料表',29113.0,'PRD','frmPRSPositionBasis','','IMES','2020-11-09 15:01:20.000',1,1,'','PS_PositionBasis_C.dll','PD213',0,'')
GO
UPDATE TBLSYSFUNCTION SET [EXECUTIONFILE]=N'SD_PDLinePositionBasis_SMES_M.dll' 
WHERE ([FUNCTIONNO]=N'POSITION BASIS') 
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS(PAGEMODE,PAGESCRIPT,ACTIVE,DESCRIPTION,CREATOR,CREATEDATE) VALUES('GET_MATERIAL_NO_CHECK','SELECT MATERIALSN_C,PRODUCTSN_C FROM TBLPRDSUBOPCOLLECTION WHERE 1=1 {{where}}',1,'获取序号物料检验信息','DS',CURRENT_TIMESTAMP)
GO

GO
INSERT INTO TBLSYSFUNCTION([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], [EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY]) VALUES (N'PD_MaintenanceItem_A', N'检验项目导入', 34502.0, N'PRD', N'frmMaintenanceItem', NULL, N'IMES', '2018-09-25 16:29:28.930', 1, 0, NULL, N'PD_MaintenanceItem_A.dll', N'PRD502', 0, NULL);
GO
update TBLSYSPARAMETER set PARAMETERVALUE='http://10.1.61.240:38080/axis2/services/ERPIService?wsdl' where PARAMETERTYPE = 'SysInfo' AND PARAMETERNO = 'PLMWebService'
GO
alter table TBLPRDSUBOPCOLLECTION add AUTOSN_C numeric(1, 0),POSITIONNO_C NVARCHAR(10),PRODUCTNO_C NVARCHAR(10),KSN_C numeric(1, 0);
GO

GO

GO
alter table TBLPRDSUBOPCOLLECTION_MTL add POSITIONNO_C NVARCHAR(10),PRODUCTNO_C NVARCHAR(10);
GO

GO

GO
UPDATE TBLSYSFUNCTION SET  [EXECUTIONFILE]=N'PD_ProductTypeBasis_SMES_M.dll'
WHERE ([FUNCTIONNO]=N'PRD TYPE') 

GO

GO

GO
INSERT INTO TBLSYSFUNCTION ([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], [EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY])
 VALUES (N'SN COLLECTION', N'序号收集', '28109.0', N'PRD', N'frmSubOPCollection', NULL, N'IMES', '2020-11-17 15:01:23.000', '1', '0', NULL, N'PD_SubOPCollection_SMES_M.dll', N'PD109', '0', NULL);

GO

GO

GO

GO

GO

GO
alter TABLE TBLPRDLABELMAP add CUSTOMERNO_C nvarchar(50) NULL,CUSTOMERNAME_C nvarchar(255)NULL;

GO

GO

GO
UPDATE TBLSYSFUNCTION SET EXECUTIONFILE='PD_ProductLabelBasis_SMES_M.dll'
WHERE FUNCTIONNO = 'PRODUCT LABEL MAP BASIS'
GO

GO

GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'PRODUCTNO_info_get_C', N'Select DISTINCT A.PRODUCTNO product_no, B.PRODUCTNAME product_name,A.PRODUCTVERSION product_version,A.MOUNITNO mounitno,A.MOTYPENO motypeno,A.FACTORYNO factoryno From TBLOEMOBASIS A  
Inner Join tblPRDProductBasis B On A.PRODUCTNO = B.PRODUCTNO and A.PRODUCTVERSION = B.PRODUCTVERSION where 1=1 {where}', N'1', N'产品编号信息获取', N'DS', '2020-11-25 09:50:13.240', N'DS', '2020-11-25 09:50:13.240');
GO

GO

GO

GO

GO

GO

GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'LOTNO_info_get_C', N'SELECT DISTINCT LOTNO FROM TBLWIPKITTINGCONFIRM_C WHERE 1=1', N'1', N'齐套确认生产批号获取', N'DS', '2020-11-25 09:50:13.240', N'DS', '2020-11-25 09:50:13.240'); 
GO
INSERT INTO tblRPTReportBasis ([REPORTID], [REPORTTYPE], [SUBSCRIBETYPE], [CREATOR], [CREATEDATE], [REPORTNAME], [REPORTLEVEL], [REPORTSCRIPT], [REPORTDBTYPE], [REPORTURLLINK], [DISPLAYTYPE]) 
VALUES (N'C01', 2, 1,  N'DS', '2020-11-25 09:50:13.240', N'齐套确认查詢',0, N'SELECT A.*,B.EQUIPMENTNO,B.OPNO FROM TBLWIPKITTINGCONFIRM_C AS A OUTER APPLY (SELECT TOP 1 * FROM TBLWIPDISPATCHSTATE WHERE LOTNO = A.LOTNO) AS B WHERE A.DELIVERYSTATUS <> ''2'' UNION SELECT A.*,B.EQUIPMENTNO,B.OPNO FROM TBLWIPKITTINGCONFIRM_C AS A OUTER APPLY (SELECT TOP 1 * FROM TBLWIPDISPATCHSTATE WHERE LOTNO = A.LOTNO) AS B WHERE A.DELIVERYSTATUS = ''2'' AND datediff(day,A.CREATETIME,getdate())= 0',0,'',9);
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'OP_EQP_info_get_C', N'SELECT B.ObjectNo AS EQUIPMENTNO,C.EQUIPMENTNAME FROM tblOPArea A LEFT JOIN TBLSMDAREARELATION B ON A.AreaNo = B.CONTAINAREANO LEFT JOIN TBLEQPEQUIPMENTBASIS C ON B.OBJECTNO = C.EquipmentNO WHERE A.DefaultArea = 1 AND B.ObjectType = ''2'' {where}', N'1', N'自动派工作业站资源设备获取', N'DS', '2020-11-25 09:50:13.240', N'DS', '2020-11-25 09:50:13.240'); 
GO
INSERT INTO TBLSYSFUNCTION([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], 
[EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY]) 
VALUES 
(N'E02M', N'派工导入作业', 12189.0, N'MWIP', NULL, NULL, N'SMES', '2020-12-01 12:29:28.930', 1, 0, NULL, NULL, NULL, 0, 'E02M');
GO
INSERT INTO TBLSYSFUNCTION([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], 
[EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY]) 
VALUES 
(N'E04M', N'齐套确认作业', 12149.0, N'MWIP', NULL, NULL, N'SMES', '2020-12-01 12:29:28.930', 1, 0, NULL, NULL, NULL, 0, 'E04M');
GO
INSERT INTO TBLSYSFUNCTION([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], 
[EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY]) 
VALUES 
(N'E05M', N'物料不良明细导入作业', 12145.0, N'MWIP', NULL, NULL, N'SMES', '2020-12-01 12:29:28.930', 1, 0, NULL, NULL, NULL, 0, 'E05M');
GO
INSERT INTO TBLSYSFUNCTION([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], 
[EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY]) 
VALUES 
(N'E06M', N'实际用料确认作业', 12145.0, N'MWIP', NULL, NULL, N'SMES', '2020-12-01 12:29:28.930', 1, 0, NULL, NULL, NULL, 0, 'E06M');
GO
INSERT INTO tblRPTReportBasis ([REPORTID], [REPORTTYPE], [SUBSCRIBETYPE], [CREATOR], [CREATEDATE], [REPORTNAME], [REPORTLEVEL], [REPORTSCRIPT], [REPORTDBTYPE], [REPORTURLLINK], [DISPLAYTYPE]) 
VALUES (N'C02', 2, 1,  N'DS', '2020-11-25 09:50:13.240', N'BOM实际用料查詢',0, N'SELECT t.*
FROM (
SELECT A.BASELOTNO AS LOTNO,B.OPNO,A.MONO,B.CURQTY,A.PRODUCTNO,A.PRODUCTVERSION,C.PRODUCTNAME,
CASE B.STATUS
   WHEN 0 THEN N''0:待進站''
   WHEN 1 THEN N''1:生產中''
   WHEN 2 THEN N''2:暫停''
   WHEN 5 THEN N''5:外包中''
   WHEN 11 THEN N''11:良品線邊倉''
   WHEN 12 THEN N''12:不良品線邊倉''
   WHEN 6 THEN N''6:網狀製程未成套''
   WHEN 9 THEN N''9:檢驗中''
   WHEN 10 THEN N''10:外包部分回貨''
   WHEN 20 THEN N''20:外包指定結案''
   WHEN 99 THEN N''99:轉庫結批''
  END STATUS,
CASE B.EVENTTIME
            WHEN (SELECT EVENTTIME FROM TBLWIPLOTSTATE WHERE STATUS IN (11,12) AND LOTNO = B.LOTNO AND STATUS = B.STATUS AND OPNO = B.OPNO) THEN CONVERT(varchar(100),B.EVENTTIME,25) 
      WHEN (SELECT EVENTTIME FROM TBLWIPLOTSTATE WHERE STATUS NOT IN (11,12) AND LOTNO = B.LOTNO AND STATUS = B.STATUS AND OPNO = B.OPNO) THEN  '''' END AS ENDDATE,
CASE B.STATUS
         WHEN 11 THEN ''已完工''
   WHEN 12 THEN ''已完工''
   ELSE ''未完工''
  END LOTSTATUS
FROM TBLWIPLOTBASIS A
LEFT JOIN TBLWIPLOTSTATE B ON A.BASELOTNO = B.LOTNO 
LEFT JOIN TBLPRDPRODUCTBASIS C ON A.PRODUCTNO = C.PRODUCTNO AND A.PRODUCTVERSION = C.PRODUCTVERSION
) t
WHERE 1=1',0,'',9); 
GO
update TBLSYSFUNCTION set EXECUTIONFILE='OP_OPBasis_SMES_M.dll' where FUNCTIONNO='OP BASIS'
GO
ALTER TABLE TBLOPBASIS ADD Isgeneratelist varchar(10) NULL
GO
update TBLSYSPARAMETER set PARAMETERVALUE='http://10.1.61.240:38080/axis2/services/ERPIService?wsdl' where PARAMETERTYPE = 'SysInfo' AND PARAMETERNO = 'PLMWebService'
GO
INSERT INTO TBLSYSFUNCTION([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], [EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY]) VALUES (N'PM_eqpsusreasons_A', N'设备保养暂停原因基本资料', 34502.0, N'PM', N'frmEqpsusReasons', NULL, N'IMES', '2020-12-04 15:01:19.000', 1, 1, N'TBLEQPSUSREASONS', N'PM_eqpsusreasons_A.dll', N'PM502', 0, NULL);

GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'MTL_info_get_C', N'SELECT MATERIALNO,MATERIALNAME,UNITNO FROM TBLMTLMATERIALBASIS', N'1', N'BOM确认物料获取', N'DS', '2020-11-25 09:50:13.240', N'DS', '2020-11-25 09:50:13.240'); 
GO
UPDATE TBLSYSPAGENUMBERINFOBASIS SET
[PAGESCRIPT]=N'select DISTINCT a.LOTNO,b.mono,b.productno,b.productversion,f.opno,g.OPNAME,e.productname,a.QTY,a.workdate,h.materialno,j.MATERIALNAME,d.moqty,h.stdqty
 from TBLWIPLOTBASIS b
 LEFT JOIN TBLOEMOBASIS d ON b.MONO = d.MONO 
and b.productversion = d.productversion
and b.productno = d.productno
LEFT JOIN TBLPRDPRODUCTBASIS e ON d.productno = e.productno AND e.productversion = d.productversion
LEFT JOIN TBLWIPLOTSTATE f ON f.LOTNO = b.BASELOTNO
LEFT JOIN TBLOPBASIS g ON f.opno = g.opno
LEFT JOIN TBLWIPDISPATCHSTATE a ON b.baselotno = a.LOTNO  and g.opno = a.opno
 LEFT JOIN TBLOEMOMATERIALLIST h 
on d.mono = h.mono
LEFT JOIN TBLMTLMATERIALBASIS j ON j.MATERIALNO = h.MATERIALNO WHERE 1=1 {where} ', [ACTIVE]=N'1', [DESCRIPTION]=N'拌料信息获取', [CREATOR]=N'DS', [CREATEDATE]='2020-11-25 09:50:13.240', [MODIFY]=N'DS', [MODIFYDATE]='2020-11-25 09:50:13.240' 
WHERE ([PAGEMODE]=N'Mixing_materials_info_get_C')


GO

GO

GO

GO

GO

GO

GO

GO

GO
INSERT INTO TBLSYSFUNCTION ([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], [EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY]) 
VALUES (N'B013A', N'拌料作业工作平台', '12149.0', N'MWIP', NULL, NULL, N'SMES', '2020-12-01 12:29:28.930', '1', '0', NULL, NULL, NULL, '0', N'B013A');
GO

GO

GO

GO

GO

GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) VALUES (N'28_c', N'  Select PositionNo As page_no, POSITIONNAME as page_name, PRSSEQ as page_prsseq  
 From  TBLPRSPOSITIONBASIS_C
 Where 1=1 {where} Order by page_prsseq 
  ', N'1', N'Y型流水线工位機設定工位查詢', N'SYSTEM', '2020-12-08 16:50:12.790', N'SYSTEM', '2020-12-08 16:50:12.790');

GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) VALUES (N'27_c', N'  Select  distinct b.opno As page_no,b.opname As page_name,b.DESCRIPTION As page_desc  
 From  TBLOPAREA a 
 join TBLOPBASIS b on a.OPNO = b.OPNO  
 Where 1=1 {where}  Order by page_no   ', N'1', N'Y型流水线工位機設定作業站查詢', N'SYSTEM', '2020-11-13 09:50:12.780', N'SYSTEM', '2020-12-08 09:50:12.780');
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'BLOTNOMaterial_info_get_C', N'select * from TBLCUSMOMIXMATERIALS where 1=1 {where}', N'1', N'拌料单物料信息获取', N'DS', '2020-12-14 09:50:13.240', N'DS', '2020-12-14 09:50:13.240');

GO

GO

GO

GO

GO

GO

GO
INSERT INTO TBLSYSFUNCTION ([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], 
[MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], 
[EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY]) 
VALUES (N'EQUIPMENT REPAIRQUERY', N'设备维修工作平台', '12149.0', N'MWIP', NULL, NULL, 
N'SMES', '2020-12-15 12:29:28.930', '1', '0', NULL, NULL, NULL, '0', N'A0601A');
GO
INSERT INTO TBLSYSFUNCTION ([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], 
[MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], 
[EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY]) 
VALUES (N'Y Serial number collection', N'Y型流水线序号收集', '12149.0', N'MWIP', NULL, NULL, 
N'SMES', '2020-12-23 12:29:28.930', '1', '0', NULL, NULL, NULL, '0', N'E01A');
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'PROPERTYNO_info_get_C', 
N'select DEFAULTVALUE from TBLOPPROPERTY where 1=1 {where}', N'1', N'作业站BL01属性获取', N'DS', '2020-12-25 09:50:13.240', N'DS', '2020-12-25 09:50:13.240');

GO
INSERT INTO [dbo].[TBLSYSFUNCTION]([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], [EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY]) VALUES (N'Equipment maintenance task allocation platform', N'设备维修任务分配平台', 37719.0, N'MWIP', NULL, NULL, N'IMES', '2020-12-29 17:40:25.000', 1, 0, NULL, NULL, N'WP719', 0, N'B0315A');
GO
update TBLSYSFUNCTION set EXECUTIONFILE='PM_EQPTypeSOPBasis_M.dll' where FUNCTIONNO='EQPTYPE SOP BASIS'
GO
alter TABLE TBLPRDSUBOPCOLLECTION add AREANO_C nvarchar(50) NULL,OPNAME_C nvarchar(100) NULL;
GO

GO
INSERT INTO tblSYSParameter (PARAMETERTYPE,PARAMETERNO,PARAMETERVALUE,PARAMETERVISABLE) VALUES ('SysInfo','H5url','http://10.1.61.242/SMES_Test_Services/InvokeJSON',1)
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'SUB_info_get_C', N'SELECT SUBSTITUTIONNO,SUBSTITUTIONNAME,SUBSTITUTIONTYPE FROM TBLPMSUBSTITUTIONBASIS', N'1', N'备品资料获取', N'DS', '2020-11-25 09:50:13.240', N'DS', '2020-11-25 09:50:13.240'); 
GO
INSERT INTO TBLSYSFUNCTION([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], 
[EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY]) 
VALUES 
(N'E08M', N'不良原因描述作业', 12149.0, N'MWIP', NULL, NULL, N'SMES', '2020-12-01 12:29:28.930', 1, 0, NULL, NULL, NULL, 0, 'E08M');
GO
INSERT INTO tblRPTReportBasis ([REPORTID], [REPORTTYPE], [SUBSCRIBETYPE], [CREATOR], [CREATEDATE], [REPORTNAME], [REPORTLEVEL], [REPORTSCRIPT], [REPORTDBTYPE], [REPORTURLLINK], [DISPLAYTYPE]) 
VALUES (N'C03', 2, 1,  N'DS', '2020-11-25 09:50:13.240', N'不良原因描述查詢',0, N'SELECT A.*,B.REASONNAME,C.PRODUCTNO,D.PRODUCTNAME FROM tblWIPCont_PCSError AS A LEFT JOIN TBLQCREASONBASIS AS B ON A.ReasonNo = B.REASONNO LEFT JOIN TBLWIPLOTBASIS C ON C.BASELOTNO = A.LotNo LEFT JOIN TBLPRDPRODUCTBASIS D ON D.PRODUCTNO = C.PRODUCTNO WHERE A.ReasonNo NOT IN (''合格'',''不合格'')',0,'',9); 
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'reson_lot_get_C', N'SELECT DISTINCT LOTNO FROM tblWIPCont_PCSError WHERE 1=1', N'1', N'不良原因生产批号获取', N'DS', '2020-11-25 09:50:13.240', N'DS', '2020-11-25 09:50:13.240'); 
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'reson_position_get_C', N'SELECT DISTINCT PositionNo FROM tblWIPCont_PCSError WHERE 1=1', N'1', N'不良原因工位获取', N'DS', '2020-11-25 09:50:13.240', N'DS', '2020-11-25 09:50:13.240');
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'reson_sn_get_C', N'SELECT DISTINCT PCSNo FROM tblWIPCont_PCSError WHERE 1=1', N'1', N'不良原因SN获取', N'DS', '2020-11-25 09:50:13.240', N'DS', '2020-11-25 09:50:13.240');
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'reson_reason_get_C', N'SELECT DISTINCT ReasonNo FROM tblWIPCont_PCSError WHERE ReasonNo NOT IN (''合格'',''不合格'')', N'1', N'不良原因获取', N'DS', '2020-11-25 09:50:13.240', N'DS', '2020-11-25 09:50:13.240');
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE],
 [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'equipment_reason_get_C', N'Select DISTINCT a.ReasonNo As page_no, b.ReasonName As page_name, b.Description As page_desc,REASONSUBTYPE
 From tblEQPEquipmentReason a join TBLQCREASONBASIS b on a.ReasonNo=B.ReasonNo
 Where b.IssueState = 2 AND REASONSUBTYPE IN(''DOWN'',''MAINTAIN'') Order by page_no', N'1', N'取得設備原因', N'DS', '2020-11-13 09:50:15.620', N'DS', '2020-11-13 09:50:15.620');

GO
INSERT INTO TBLSYSFUNCTION([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], 
[EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY]) 
VALUES 
(N'M90', N'设备维修任务分配平台手机端作业', 12189.0, N'MWIP', NULL, NULL, N'SMES', '2020-12-01 12:29:28.930', 1, 0, NULL, NULL, NULL, 0, 'M90');
GO
alter TABLE TBLEQPEQUIPMENTBASIS add MOREWORK nvarchar(1) NULL
GO

GO

GO
UPDATE TBLSYSFUNCTION SET [EXECUTIONFILE]=N'EP_EquipmentBasis_SMES_C.dll' WHERE ([FUNCTIONNO]=N'EQP BASIS') 
GO

GO

GO
alter TABLE TBLOEMOMTLCONFIRM_C add REMARK nvarchar(255) NULL
GO

GO

GO
alter TABLE TBLWIPKITTINGCONFIRM_C add REMARK nvarchar(255) NULL
GO

GO

GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'EQP_info_get_C', N'SELECT DISTINCT EQUIPMENTNO,EQUIPMENTNAME FROM TBLEQPEQUIPMENTBASIS WHERE EQUIPMENTNO IS NOT NULL AND EQUIPMENTNO <> ''''', N'1', N'齐套确认设备编号获取', N'DS', '2020-11-25 09:50:13.240', N'DS', '2020-11-25 09:50:13.240'); 
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'OP_info_get_C', N'SELECT DISTINCT OPNO,OPNAME FROM TBLOPBASIS WHERE OPNO IS NOT NULL AND OPNO <> ''''', N'1', N'齐套确认设备编号获取', N'DS', '2020-11-25 09:50:13.240', N'DS', '2020-11-25 09:50:13.240'); 

GO
INSERT INTO TBLSYSFUNCTION(FUNCTIONNO,FUNCTIONNAME,FUNCTIONORDER,MODULENO,FORMNAME,WEBURL,CREATOR,CREATEDATE,PRIVOPTION,ISSUEOPTION,ISSUETABLE,EXECUTIONFILE,FUNCTIONKEY,ExecutionMode,H5FUNCTIONKEY)
VALUES ('ACC QCLIST','模治具点检基本资料表',29114.0,'ACC','frmACCQCListBasis','','IMES','2021-04-19 15:01:20.000',1,0,'','ACC_QCListBasis_C.dll','AC601',0,'')
GO
CREATE TABLE [dbo].[TBLACCQCLISTBASIS](
 [QCLISTNO] [nvarchar](100) NOT NULL,
 [QCLISTNAME] [nvarchar](100) NULL,
 [QCTYPE] [numeric](2, 0) NOT NULL,
 [UNVALIDACTION] [numeric](2, 0) NULL,
 [DESCRIPTION] [nvarchar](255) NULL,
 [CREATOR] [nvarchar](10) NULL,
 [CREATEDATE] [datetime] NULL,
 [ValidDate] [numeric](8, 0) NULL,
 [ValidLot] [numeric](8, 0) NULL,
 [ValidQTY] [numeric](8, 0) NULL,
 CONSTRAINT [PK_TBLACCQCLISTBASIS] PRIMARY KEY CLUSTERED 
(
 [QCLISTNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBLACCQCLISTBASIS] ADD  DEFAULT ((-1)) FOR [ValidDate]
GO

ALTER TABLE [dbo].[TBLACCQCLISTBASIS] ADD  DEFAULT ((-1)) FOR [ValidLot]
GO

ALTER TABLE [dbo].[TBLACCQCLISTBASIS] ADD  DEFAULT ((-1)) FOR [ValidQTY]
GO
GO
CREATE TABLE [dbo].[TBLACCQCLISTDETAIL](
 [QCLISTNO] [nvarchar](100) NOT NULL,
 [QCORDER] [numeric](2, 0) NOT NULL,
 [QCITEM] [nvarchar](1000) NULL,
 [QCTYPE] [numeric](1, 0) NOT NULL,
 [STDVALUE] [nvarchar](12) NULL,
 [MAXIVALUE] [nvarchar](12) NULL,
 [MINIVALUE] [nvarchar](12) NULL,
 [INPUTDATACOUNT] [numeric](2, 0) NOT NULL,
 [INSPECTIONMETHOD] [nvarchar](100) NULL,
 [INSPECTIONSTANDARDS] [nvarchar](100) NULL,
 [DataitemNO] [nvarchar](50) NULL,
 [AutoDataQuery] [numeric](1, 0) NULL,
 CONSTRAINT [PK_TBLACCQCLISTDETAIL] PRIMARY KEY CLUSTERED 
(
 [QCLISTNO] ASC,
 [QCORDER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBLACCQCLISTDETAIL] ADD  DEFAULT ((1)) FOR [INPUTDATACOUNT]
GO

ALTER TABLE [dbo].[TBLACCQCLISTDETAIL] ADD  DEFAULT ((0)) FOR [AutoDataQuery]
GO

GO
UPDATE TBLSYSFUNCTION SET EXECUTIONFILE='AC_AccessoryBasis_C.dll' WHERE FUNCTIONNO='ACC BASIS'
GO
alter TABLE tblEQPAccessoryBasis add QCLISTNO nvarchar(50) NULL
GO
alter TABLE tblEQPAccessoryBasisLog add QCLISTNO nvarchar(50) NULL
GO
CREATE TABLE [dbo].[tblAccCheckUpRate](
 [AccNo] [nvarchar](50) NOT NULL,
 [AccCheckUp] [nvarchar](1) NOT NULL,
 [AccCheckUpRate] [nvarchar](1) NOT NULL,
 [QcListNo] [nvarchar](50) NULL,
 [IsEnabled] [numeric](1, 0) NOT NULL,
 [Creator] [nvarchar](10) NULL,
 [CreateDate] [datetime] NULL,
 CONSTRAINT [PK_tblAccCheckUpRate] PRIMARY KEY CLUSTERED 
(
 [AccNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'ACC_inspection_frequency_get_C', N'Select (Case AccCheckUpRate When 0 Then ''月'' When 1 Then ''週'' When 2 Then ''日'' When 3 Then ''時'' End) AccCheckUpRate,ra.QcListNo, BA.QCLISTNAME, AccCheckUpRate qc_frequency From tblAccCheckUpRate ra Join TBLACCQCLISTBASIS ba on ra.QcListNo = BA.QCLISTNO Where IsEnabled = 1 {Where}', N'1', N'模治具点检频率设定获取', N'DS', '2020-11-25 09:50:13.240', N'DS', '2020-11-25 09:50:13.240'); 


GO
CREATE TABLE [dbo].[TBLWIPACCQCLISTLOG](
 [QCLISTSERIAL] [nvarchar](100) NOT NULL,
 [AccessoryNo] [nvarchar](50) NOT NULL,
 [QCLISTNO] [nvarchar](100) NOT NULL,
 [LOTSERIAL] [nvarchar](55) NULL,
 [LOGGROUPSERIAL] [nvarchar](55) NULL,
 [QCRESULT] [numeric](1, 0) NOT NULL,
 [DESCRIPTION] [nvarchar](255) NULL,
 [CREATOR] [nvarchar](10) NULL,
 [CREATEDATE] [datetime] NULL,
 [REVISER] [nvarchar](10) NULL,
 [REVISEDATE] [datetime] NULL,
 [ACCCheckUpRate] [nvarchar](1) NOT NULL,
 CONSTRAINT [PK_TBLWIPACCQCLISTLOG] PRIMARY KEY CLUSTERED 
(
 [QCLISTSERIAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

GO
CREATE TABLE [dbo].[TBLWIPACCQCLISTDETAIL](
 [QCLISTSERIAL] [nvarchar](120) NOT NULL,
 [QCITEM] [nvarchar](1000) NOT NULL,
 [QCRESULT] [numeric](1, 0) NOT NULL,
 [INPUTVALUE] [nvarchar](50) NULL,
 [STDVALUE] [nvarchar](12) NULL,
 [MAXIVALUE] [nvarchar](12) NULL,
 [MINIVALUE] [nvarchar](12) NULL,
 [INPUTDATACOUNT] [numeric](2, 0) NOT NULL,
 [D01] [nvarchar](50) NULL,
 [D02] [nvarchar](50) NULL,
 [D03] [nvarchar](50) NULL,
 [D04] [nvarchar](50) NULL,
 [D05] [nvarchar](50) NULL,
 [D06] [nvarchar](50) NULL,
 [D07] [nvarchar](50) NULL,
 [D08] [nvarchar](50) NULL,
 [D09] [nvarchar](50) NULL,
 [D10] [nvarchar](50) NULL,
 [QCORDER] [numeric](2, 0) NOT NULL,
 [QCTYPE] [numeric](1, 0) NULL,
 CONSTRAINT [PK_TBLWIPACCQCLISTDETAIL] PRIMARY KEY CLUSTERED 
(
 [QCLISTSERIAL] ASC,
 [QCITEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBLWIPACCQCLISTDETAIL] ADD  DEFAULT ((1)) FOR [INPUTDATACOUNT]
GO

ALTER TABLE [dbo].[TBLWIPACCQCLISTDETAIL] ADD  DEFAULT ((-99)) FOR [QCORDER]
GO
GO
INSERT INTO TBLSYSFUNCTION([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], 
[EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY]) 
VALUES 
(N'E07M', N'结束生产作业', 12149.0, N'MWIP', NULL, NULL, N'SMES', '2020-12-01 12:29:28.930', 1, 0, NULL, NULL, NULL, 0, 'E07M');
GO

INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE],
 [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'cus_area_info_get', N'select DISTINCT areano from TBLWIPLOTSTATE Where 1=1{where}', N'1', N'取得作业站对应区域', N'DS', '2020-11-13 09:50:15.620', N'DS', '2020-11-13 09:50:15.620');
GO
update TBLSYSFUNCTION set EXECUTIONFILE = 'SS_SerialRuleConfig_SMES_M.dll' WHERE functionno = 'SERIAL RULE CONFIG'

GO
INSERT INTO TBLSYSFUNCTION ([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO],
 [FORMNAME], [WEBURL], [CREATOR], 
[CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], [EXECUTIONFILE], [FUNCTIONKEY], 
[ExecutionMode], [H5FUNCTIONKEY]) 
VALUES (N'E10A', N'试模管理', '12149.0', N'MWIP', NULL, NULL, N'SMES', '2020-12-01 12:29:28.930', '1', '0', 
NULL, NULL, NULL, '0', N'E10A');
GO

INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE],
 [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'CUS_TBLCUSMOLDBASIS_info_get', N'select TESTMOLDNO from TBLCUSMOLDBASIS
 Where 1=1  {where} ORDER BY TESTMOLDNO desc', N'1', N'试模记录单号查询', N'DS', '2021-04-13 09:50:15.620', N'DS', '2021-04-13 09:50:15.620');
GO

INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE],
 [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'CUS_mold_info_get', N'select * from TBLCUSMOLDBASIS
 Where 1=1  {where} Order by TESTMOLDNO', N'1', N'试模管理查询', N'DS', '2021-04-13 09:50:15.620', N'DS', '2021-04-13 09:50:15.620');
GO
INSERT INTO TBLSYSFUNCTION ([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO],
 [FORMNAME], [WEBURL], [CREATOR], 
[CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], [EXECUTIONFILE], [FUNCTIONKEY], 
[ExecutionMode], [H5FUNCTIONKEY]) 
VALUES (N'B0317A', N'注塑标签打印', '12149.0', N'MWIP', NULL, NULL, N'SMES', '2020-12-01 12:29:28.930', '1', '0', 
NULL, NULL, NULL, '0', N'B0317A');
GO
INSERT INTO TBLSYSFUNCTION ([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO],
 [FORMNAME], [WEBURL], [CREATOR], 
[CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], [EXECUTIONFILE], [FUNCTIONKEY], 
[ExecutionMode], [H5FUNCTIONKEY]) 
VALUES (N'B0181A', N'自检', '12149.0', N'MWIP', NULL, NULL, N'SMES', '2020-12-01 12:29:28.930', '1', '0', 
NULL, NULL, NULL, '0', N'B0181A');
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE],
 [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'CUS_TBLCUSContPCSNoLOG_info_get', N'select top 1 PCSNO from TBLCUSContPCSNoLOG
 Where 1=1  {where} ORDER BY createdate DESC', N'1',
 N'成品序号查询', N'DS', '2021-04-13 09:50:15.620', N'DS', '2021-04-13 09:50:15.620');

GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE],
 [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'lot_result_info_get', N'select STATUS from tblWIPLotState
 Where 1=1  {where}', N'1', N'生产批状态查询', N'DS', '2021-04-13 09:50:15.620', N'DS', '2021-04-13 09:50:15.620'); 
GO
CREATE TABLE [dbo].[TBLWIPLOTREMARK_C](
 [PRODUCTNO] [nvarchar](50) NOT NULL,
 [PRODUCTVERSION] [nvarchar](50) NOT NULL,
 [LOTNO] [nvarchar](50) NOT NULL,
 [OPNO] [nvarchar](50) NOT NULL,
 [QTY] [numeric](12, 6) NULL,
 [DISPATCHTIME] [datetime] NOT NULL,
 [MACHINENO] [nvarchar](50) NOT NULL,
 [ORDERNO] [nvarchar](50) NULL,
 [WORKNO] [nvarchar](50) NULL,
 [WORKSHOPNO] [nvarchar](50) NULL,
 [ACCNO] [nvarchar](50) NULL,
 [CUSTOMERNAME] [nvarchar](50) NULL,
 CONSTRAINT [PK_TBLWIPLOTREMARK_C] PRIMARY KEY CLUSTERED 
(
 [PRODUCTNO] ASC,
 [PRODUCTVERSION] ASC,
 [LOTNO] ASC,
 [OPNO] ASC,
 [DISPATCHTIME] ASC,
 [MACHINENO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBLWIPLOTREMARK_C] ADD  CONSTRAINT [DF_TBLWIPLOTREMARK_C_QTY]  DEFAULT ((0)) FOR [QTY]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'产品编号' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBLWIPLOTREMARK_C', @level2type=N'COLUMN',@level2name=N'PRODUCTNO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'产品版本' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBLWIPLOTREMARK_C', @level2type=N'COLUMN',@level2name=N'PRODUCTVERSION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'生产批号' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBLWIPLOTREMARK_C', @level2type=N'COLUMN',@level2name=N'LOTNO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'作业站编号' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBLWIPLOTREMARK_C', @level2type=N'COLUMN',@level2name=N'OPNO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'派工数量' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBLWIPLOTREMARK_C', @level2type=N'COLUMN',@level2name=N'QTY'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'派工时间' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBLWIPLOTREMARK_C', @level2type=N'COLUMN',@level2name=N'DISPATCHTIME'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'派工设备' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBLWIPLOTREMARK_C', @level2type=N'COLUMN',@level2name=N'MACHINENO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'订单编号' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBLWIPLOTREMARK_C', @level2type=N'COLUMN',@level2name=N'ORDERNO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'工作令' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBLWIPLOTREMARK_C', @level2type=N'COLUMN',@level2name=N'WORKNO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'生产车间' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBLWIPLOTREMARK_C', @level2type=N'COLUMN',@level2name=N'WORKSHOPNO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'模具号' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBLWIPLOTREMARK_C', @level2type=N'COLUMN',@level2name=N'ACCNO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'客户名称' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBLWIPLOTREMARK_C', @level2type=N'COLUMN',@level2name=N'CUSTOMERNAME'
GO

GO
CREATE TABLE [dbo].[TBLCUSEMPLOYEE_OUT](
 [LotNo] [nvarchar](50) NOT NULL,
 [OPNo] [nvarchar](50) NOT NULL,
 [EventTime] [datetime] NOT NULL,
 [EmployeeNo] [nvarchar](50) NOT NULL,
 [EmployeeName] [nvarchar](50) NULL,
 [MachineNo] [nvarchar](50) NULL,
 CONSTRAINT [PK_TBLCUSEMPLOYEE_OUT] PRIMARY KEY CLUSTERED 
(
 [LotNo] ASC,
 [OPNo] ASC,
 [EventTime] ASC,
 [EmployeeNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
GO
CREATE TABLE [dbo].[TBLCUSPLOTCHECKIN_UP](
 [GUID] [nvarchar](50) NOT NULL,
 [UpLotNo] [nvarchar](50) NULL,
 [UpMoNo] [nvarchar](50) NULL,
 [UpOpNo] [nvarchar](50) NULL,
 [LotNo] [nvarchar](50) NULL,
 [OpNo] [nvarchar](50) NULL,
 [MachineNo] [nvarchar](50) NULL,
 [Creator] [nvarchar](50) NULL,
 [CreateTime] [datetime] NULL,
 CONSTRAINT [PK_TBLCUSPLOTCHECKIN_UP] PRIMARY KEY CLUSTERED 
(
 [GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
GO
CREATE TABLE [dbo].[TBLCUSREASONTYPEBASIS](
 [REASONTYPE] [numeric](2, 0) NOT NULL,
 [REASONTYPENAME] [nvarchar](50) NULL,
 [DESCRIPTION] [nvarchar](255) NULL,
 [CREATOR] [nvarchar](10) NULL,
 [CREATEDATE] [datetime] NULL,
 CONSTRAINT [PK_TBLCUSREASONTYPEBASIS] PRIMARY KEY CLUSTERED 
(
 [REASONTYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'0：气密性；1：功能测试' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBLCUSREASONTYPEBASIS', @level2type=N'COLUMN',@level2name=N'REASONTYPE'
GO
GO
CREATE TABLE [dbo].[TBLCUSREASONBASIS](
 [REASONNO] [nvarchar](20) NOT NULL,
 [REASONNAME] [nvarchar](100) NOT NULL,
 [REASONTYPE] [numeric](2, 0) NULL,
 [DESCRIPTION] [nvarchar](255) NULL,
 [CREATOR] [nvarchar](10) NULL,
 [CREATEDATE] [datetime] NULL,
 CONSTRAINT [PK_TBLCUSREASONBASIS] PRIMARY KEY CLUSTERED 
(
 [REASONNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'work_return_reason_get_c', N'SELECT * FROM TBLCUSREASONTYPEBASIS WHERE 1=1', N'1', N'返工返修原因类别获取', N'DS', '2021-06-25 09:50:13.240', N'DS', '2021-06-25 09:50:13.240'); 
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'work_return_reason_no_get_c', N'SELECT * FROM TBLCUSREASONBASIS WHERE 1=1', N'1', N'返工返修原因编号获取', N'DS', '2021-06-25 09:50:13.240', N'DS', '2021-06-25 09:50:13.240'); 
GO
CREATE TABLE [dbo].[TBLCUSRETURNREASONLOG](
 [MASTER_SID] [nvarchar](50) NOT NULL,
 [REASONNO] [nvarchar](50) NOT NULL,
 [REASONNAME] [nvarchar](100) NOT NULL,
 [REASONTYPE] [numeric](2, 0) NULL,
 [REASONTYPENAME] [nvarchar](100) NOT NULL,
 [DESCRIPTION] [nvarchar](255) NULL,
 [CREATOR] [nvarchar](10) NULL,
 [CREATEDATE] [datetime] NULL
) ON [PRIMARY]
GO

GO

INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], 
[CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) VALUES
 (N'cus_loadProduct', N'  Select DISTINCT productno As page_no, productname as page_name
 From  TBLPRSPOSITIONBASIS_C
 Where 1=1 {where} Order by page_no 
  ', N'1', N'Y型流水线工位机設定产品编号查詢', N'SYSTEM', '2020-12-08 16:50:12.790', N'SYSTEM', '2020-12-08 16:50:12.790');

GO
alter table TBLPRDSUBOPCOLLECTION add CHECKMO_C numeric(1, 0)
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], [CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) 
VALUES (N'getEquipmentNo_C', N'
 select DISTINCT lotno,equipmentno from tblWIPTemp_Equipment',
 N'1', N'设备暂存表设备编号', N'DS', '2021-09-03 15:48:59.750', N'DS', '2021-09-03 15:48:59.750');

GO
INSERT INTO TBLSYSFUNCTION ([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO],
 [FORMNAME], [WEBURL], [CREATOR], 
[CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], [EXECUTIONFILE], [FUNCTIONKEY], 
[ExecutionMode], [H5FUNCTIONKEY]) 
VALUES (N'称重标准维护', N'称重标准维护', '12149.0', N'MWIP', NULL, NULL, N'SMES', '2020-12-01 12:29:28.930', '1', '0', 
NULL, NULL, NULL, '0', N'E12A');
GO
INSERT INTO TBLSYSFUNCTION (
 [FUNCTIONNO],
 [FUNCTIONNAME],
 [FUNCTIONORDER],
 [MODULENO],
 [FORMNAME],
 [WEBURL],
 [CREATOR],
 [CREATEDATE],
 [PRIVOPTION],
 [ISSUEOPTION],
 [ISSUETABLE],
 [EXECUTIONFILE],
 [FUNCTIONKEY],
 [ExecutionMode],
 [H5FUNCTIONKEY]
)
VALUES
 (
  N'GOODS CODE WEBSITE BASIS',
  N'商品码网址设定',
  '28109.0',
  N'SYS',
  N'frmGoodsCodeWebsiteBasis',
  NULL,
  N'IMES',
  '2016-07-05 15:01:23.000',
  '1',
  '0',
  NULL,
  N'SS_GoodsCodeWebsiteBasis_SMES_A.dll',
  N'',
  '0',
  NULL
 );


GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS (
 [PAGEMODE],
 [PAGESCRIPT],
 [ACTIVE],
 [DESCRIPTION],
 [CREATOR],
 [CREATEDATE],
 [MODIFY],
 [MODIFYDATE]
)
VALUES
 (
  N'cus_sbbx_user_no_info_get',
  N'select C.UserNo user_no ,C.username user_name from TBLUSRGROUPBASIS A LEFT JOIN tblUSRUserGroup B 
ON A.GROUPNO = B.GroupNo AND B.GroupType = 0 
left join TBLUSRUSERBASIS C ON C.USERNO = B.USERNO where 1=1  {where}',
  N'1',
  N'设备报修群组用戶資料取得',
  N'SYSTEM',
  '2020-11-13 09:50:13.367',
  N'SYSTEM',
  '2020-11-13 09:50:13.367'
 );
GO
INSERT INTO TBLSYSVALUELIST ([TABLENAME], [COLUMNNAME], [COLUMNVALUE], [DISPLAYTEXT]) 
VALUES (N'TBLQCREASONBASIS', N'REASONSUBTYPE_SMES', '5', N'RUNSTATE_SMES');
INSERT INTO TBLSYSVALUELIST ([TABLENAME], [COLUMNNAME], [COLUMNVALUE], [DISPLAYTEXT]) 
VALUES (N'TBLQCREASONBASIS', N'REASONSUBTYPE_SMES', '6', N'SERVICE_SMES');
GO
UPDATE TBLSYSFUNCTION SET EXECUTIONFILE='EP_EquipmentStatusReasonBasis_SMES_M.dll'
WHERE FUNCTIONNO='EQUIPMENT STATUS REASON BASIS';
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], 
[CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) VALUES
 (N'cus_load_eqp_repair_dispatch', N'Select a.*,b.remark From  TBLCUSEQPREPAIRDISSTATE a left join tblReasonLog b on a.DISPATCHID = b.DISPATCHID
Where 1=1 {where} and datediff(hour, a.starttime,getdate())> 24 
and not exists (select * from TBLCUSREPAIRBACK c where a.DISPATCHID=c.DISPATCHID)
Order by A.DISPATCHID 
  ', N'1', N'设备维修派工查詢', N'SYSTEM', '2020-12-08 16:50:12.790', N'SYSTEM', '2020-12-08 16:50:12.790');
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], 
[CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) VALUES
 (N'cus_load_eqp_repair_no_dispatch', N' SELECT a.EQUIPMENTNO,EquipmentName,c.EQUIPMENTTYPE,a.REMARKS,REASONNO,REASONNAME,STARTTIME,a.EQPSERIALNO,AreaNo,A.USERNO,e.USERNAME,
 EQUIPMENTSTATE,C_DOWNSTATE
 FROM tblEMSEquipmentState a LEFT JOIN TBLEMSEQUIPMENTREASONS b
 ON a.EQPSERIALNO = b.EQPSERIALNO
 LEFT JOIN TBLEQPEQUIPMENTBASIS c ON a.EQUIPMENTNO = c.EQUIPMENTNO
 LEFT JOIN TBLWIPDISPATCHSET d ON d.EQUIPMENTNO = c.EQUIPMENTNO
 LEFT JOIN TBLUSRUSERBASIS e ON a.USERNO = e.USERNO
 where EQUIPMENTSTATE in(2,4)
 union all 
 SELECT f.EQUIPMENTNO,EquipmentName,c.EQUIPMENTTYPE,f.REMARKS,REASONNO,REASONNAME,f.STARTTIME,f.EQPSERIALNO,AreaNo,f.USERNO,e.USERNAME,
 f.EQUIPMENTSTATE,C_DOWNSTATE FROM TBLCUSEquipmentDownStateLog f left join tblEMSEquipmentState a  on f.EQUIPMENTNO = a.EQUIPMENTNO
   LEFT JOIN TBLEMSEQUIPMENTREASONS b
  ON f.EQPSERIALNO = b.EQPSERIALNO
 LEFT JOIN TBLEQPEQUIPMENTBASIS c ON a.EQUIPMENTNO = c.EQUIPMENTNO
LEFT JOIN TBLWIPDISPATCHSET d ON d.EQUIPMENTNO = c.EQUIPMENTNO
 LEFT JOIN TBLUSRUSERBASIS e ON f.USERNO = e.USERNO
Where 1=1 {where}
  ', N'1', N'设备维修未派工查詢', N'SYSTEM', '2020-12-08 16:50:12.790', N'SYSTEM', '2020-12-08 16:50:12.790');
GO
INSERT INTO TBLSYSFUNCTION ([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO],
 [FORMNAME], [WEBURL], [CREATOR], 
[CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], [EXECUTIONFILE], [FUNCTIONKEY], 
[ExecutionMode], [H5FUNCTIONKEY]) 
VALUES (N'注塑机数采查询', N'注塑机数采查询', '12149.0', N'MWIP', NULL, NULL, N'SMES', '2020-12-01 12:29:28.930', '1', '0', 
NULL, NULL, NULL, '0', N'E14A');
GO
CREATE TABLE TBLCUSStockStateRecord ( 
  [StockLotNo] nvarchar(50) NULL  ,
  [MaterialNo] nvarchar(50) NULL  ,
  [StockWeight] nvarchar(50) NULL  ,
  [SN] nvarchar(50) NULL  ,
  [WeighingRecord] nvarchar(1) NULL  ,
  [Weight] nvarchar(50) NULL  ,
  [WhetherStatement] nvarchar(1) NULL  ,
  [StatementTime] datetime NULL  ,
  [CreateTime] datetime NULL 
);
GO
INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO, FORMNAME, WEBURL, CREATOR, CREATEDATE, 
PRIVOPTION, ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY, ExecutionMode,H5FUNCTIONKEY) VALUES 
(N'备料记录平台', N'备料记录平台', '39999.0', N'MWIP', NULL, NULL, N'IMES', SYSDATETIME(), '1', '0', NULL, NULL, N'WP900', '0','B0319A');
GO
INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO, FORMNAME, WEBURL, CREATOR, CREATEDATE, 
PRIVOPTION, ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY, ExecutionMode,H5FUNCTIONKEY) VALUES 
(N'前置作业工作平台', N'前置作业工作平台', '39999.0', N'MWIP', NULL, NULL, N'DS', GETDATE(), '1', '0', NULL, NULL, N'WP900', '0','B0242A');
GO
create table TBLPROCESSCONFIG  
(  
EQUIPMENTNO nvarchar(50),   
PROCESS nvarchar(50),
primary key (EQUIPMENTNO,PROCESS)
)  
GO
create table TBLPROCESSRECORD  
(  
EQUIPMENTNO nvarchar(50) not null,   
PROCESS nvarchar(50),   
DELNO nvarchar(50),
BEGINTIME datetime,
ENDTIME datetime,
USERNO nvarchar(50),
MONO nvarchar(50),
FINNISHTIME datetime,
primary key (DELNO,PROCESS)
)  
GO
INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO, FORMNAME, WEBURL, CREATOR, CREATEDATE, 
PRIVOPTION, ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY, ExecutionMode,H5FUNCTIONKEY) VALUES 
(N'齐套标签打印', N'齐套标签打印', '39999.0', N'MWIP', NULL, NULL, N'DS', GETDATE(), '1', '0', NULL, NULL, N'WP900', '0','E16A');
GO
INSERT INTO TBLSYSFUNCTION([FUNCTIONNO], [FUNCTIONNAME], [FUNCTIONORDER], [MODULENO], [FORMNAME], [WEBURL], [CREATOR], [CREATEDATE], [PRIVOPTION], [ISSUEOPTION], [ISSUETABLE], [EXECUTIONFILE], [FUNCTIONKEY], [ExecutionMode], [H5FUNCTIONKEY]) VALUES (N'ProcessSetting', N'工厂默认流程设定', 34502.0, N'PRD', N'frmProcessSetting', NULL, N'IMES', '2018-09-25 16:29:28.930', 1, 0, NULL, N'PD_ProcessSetting_A.dll', N'PRD502', 0, NULL);
GO

UPDATE TBLSYSPAGENUMBERINFOBASIS SET  
[PAGESCRIPT]=N'select tabl.* from (select DISTINCT a.LOTNO,b.mono,b.productno,b.productversion,f.opno,g.OPNAME,
e.productname,a.QTY,CONVERT(VARCHAR(10),a.workdate,120) as workdate,
 1 as moqty,(SELECT SUM(RequireQty)  from TBLOEMOMATERIALLIST
GROUP BY mono having mono = d.mono) as stdqty,
(stuff((select  ''/'' +  CONVERT(varchar(90),CONVERT(float,RequireQty)) from TBLOEMOMATERIALLIST
where mono = d.mono 
 for xml path('''')),1,1,'''')) as qtySEQ,
(stuff((select  ''|'' + materialno from TBLOEMOMATERIALLIST
where mono = d.mono 
 for xml path('''')),1,1,'''')) as materialSEQ ,
(stuff((select ''|'' + MATERIALNAME from TBLOEMOMATERIALLIST h LEFT JOIN TBLMTLMATERIALBASIS j ON
j.MATERIALNO = h.MATERIALNO 
where  mono = d.mono  
 for xml path('''')),1,1,'''')) as materialnameSEQ ,
(stuff((select  ''|'' + AccessoryNo from tblPRDAccessory acc LEFT JOIN TBLWIPLOTBASIS a on acc.PRODUCTNO = a.productno
 AND  acc.productversion = a.productversion WHERE BASELOTNO = b.baselotno
 for xml path('''')),1,1,'''')) as AccessoryNo,
a.EQUIPMENTNO,b.C_BLNO,d.MOSTATE 
 from TBLWIPLOTBASIS b
 LEFT JOIN TBLOEMOBASIS d ON b.MONO = d.MONO 
and b.productversion = d.productversion
and b.productno = d.productno
LEFT JOIN TBLPRDPRODUCTBASIS e ON d.productno = e.productno AND e.productversion = d.productversion
LEFT JOIN TBLWIPLOTSTATE f ON f.LOTNO = b.BASELOTNO AND  F.STATUS NOT  IN  (''11'',''12'')
LEFT JOIN TBLOPBASIS g ON f.opno = g.opno
LEFT JOIN TBLWIPDISPATCHSTATE a ON b.baselotno = a.LOTNO  and g.opno = a.opno
 LEFT JOIN TBLOEMOMATERIALLIST h on d.mono = h.mono 
LEFT JOIN TBLMTLMATERIALBASIS j ON j.MATERIALNO = h.MATERIALNO) tabl WHERE 1=1 {where} and tabl.EQUIPMENTNO LIKE ''ZS%'' 
and tabl.materialSEQ !='''' ORDER BY tabl.EQUIPMENTNO,tabl.workdate DESC'
WHERE ([PAGEMODE]=N'Mixing_materials_info_get_C') 
GO
INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO,        
 FORMNAME, WEBURL, CREATOR, CREATEDATE,  PRIVOPTION, 
 ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY, 
 ExecutionMode,H5FUNCTIONKEY) 
VALUES  (N'B0238_1', N'入库', '39999.0', N'MWIP', '', 
         NULL, N'sMES', GETDATE(), '1', '0', 
         NULL, '', N'WIP238_1', '0','B0238_1');
     
INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO, FORMNAME, WEBURL, CREATOR, CREATEDATE,  PRIVOPTION, ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY,ExecutionMode,H5FUNCTIONKEY) 
VALUES  (N'B0238_2', N'在线', '39999.0', N'MWIP', '',  NULL, N'sMES', GETDATE(), '1', '0', NULL, '', N'WIP238_2', '0','B0238_2');

INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO, FORMNAME, WEBURL, CREATOR, CREATEDATE,  PRIVOPTION, ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY,ExecutionMode,H5FUNCTIONKEY) 
VALUES  (N'B0238_3', N'停用', '39999.0', N'MWIP', '',  NULL, N'sMES', GETDATE(), '1', '0', NULL, '', N'B0238_3', '0','B0238_3');
  
INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO, FORMNAME, WEBURL, CREATOR, CREATEDATE,  PRIVOPTION, ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY,ExecutionMode,H5FUNCTIONKEY) 
VALUES  (N'B0238_4', N'外发', '39999.0', N'MWIP', '',  NULL, N'sMES', GETDATE(), '1', '0', NULL, '', N'B0238_4', '0','B0238_4');
  
INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO, FORMNAME, WEBURL, CREATOR, CREATEDATE,  PRIVOPTION, ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY,ExecutionMode,H5FUNCTIONKEY) 
VALUES  (N'B0238_5', N'报废', '39999.0', N'MWIP', '',  NULL, N'sMES', GETDATE(), '1', '0', NULL, '', N'B0238_5', '0','B0238_5');

INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO, FORMNAME, WEBURL, CREATOR, CREATEDATE,  PRIVOPTION, ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY,ExecutionMode,H5FUNCTIONKEY) 
VALUES  (N'B0238_6', N'复用', '39999.0', N'MWIP', '',  NULL, N'sMES', GETDATE(), '1', '0', NULL, '', N'B0238_6', '0','B0238_6');
  

GO
ALTER TABLE TBLEQPACCESSORYBASIS ADD ACCSERIALNO_C INT;
 ALTER TABLE  tblEQPAccessoryBasisLog ADD ACCSERIALNO_C INT;
 ALTER TABLE tblEMSAccessoryStateLog ADD REMARK NVARCHAR2(2000);
GO
ALTER TABLE TBLWIPCONT_PCSNO ADD OLDRELATION_C NVARCHAR(50);
GO
ALTER TABLE  TBLPRDSUBOPCOLLECTION ADD CHECKMOBOM_C INT;
GO
ALTER TABLE TBLMTLMATERIALBASIS ADD STOCKTYPE_C NUMERIC(1,0);
ALTER TABLE TBLMTLMATERIALBASIS ADD XBCQTY_C NUMERIC(16,6);
ALTER TABLE TBLMTLMATERIALBASIS ADD LINEQTY_C NUMERIC(16,6);
GO
 INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO,        
 FORMNAME, WEBURL, CREATOR, CREATEDATE,  PRIVOPTION, 
 ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY, 
 ExecutionMode,H5FUNCTIONKEY) 
VALUES  (N'mobile92A', N'线边仓物料入库', '39999.0', N'MWIP', '', 
         NULL, N'sMES', GETDATE(), '1', '0', 
         NULL, '', N'mobile92A', '0','mobile92A');
     
GO

  INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO,        
 FORMNAME, WEBURL, CREATOR, CREATEDATE,  PRIVOPTION, 
 ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY, 
 ExecutionMode,H5FUNCTIONKEY) 
VALUES  (N'F0401A', N'最低库存维护', '39999.0', N'MWIP', '', 
         NULL, N'sMES', GETDATE(), '1', '0', 
         NULL, '', N'F0401A', '0','F0401A');
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS ([PAGEMODE], [PAGESCRIPT], [ACTIVE], [DESCRIPTION], 
[CREATOR], [CREATEDATE], [MODIFY], [MODIFYDATE]) VALUES
 (N'IIOT_SERIAL_NUMBER_GET', N'    SELECT PLOTNO as plot_no,InPlantSN,DeviceName,
  DisposalMethod as disposal_method, DisposalDate as Disposal_Data  FROM TBLCUSIIOTSERIALNUMBER
  ', N'1', N'IIOT处置记录查询', N'SYSTEM', '2020-11-13 09:50:12.573', N'SYSTEM', '2020-11-13 09:50:12.573');
GO
INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO,        
 FORMNAME, WEBURL, CREATOR, CREATEDATE,  PRIVOPTION, 
 ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY, 
 ExecutionMode,H5FUNCTIONKEY) 
VALUES  (N'E018A', N'外箱条码打印', '39999.0', N'MWIP', '', 
         NULL, N'sMES', GETDATE(), '1', '0', 
         NULL, '', N'E018A', '0','E018A');
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS(PAGEMODE,PAGESCRIPT,ACTIVE,DESCRIPTION,CREATOR,CREATEDATE)
VALUES('4_2',' SELECT PRODUCTNO page_no,PRODUCTNAME page_name  FROM tblPRDProductBasis WHERE 1=1 {where} GROUP BY PRODUCTNO, PRODUCTNAME',1,'产品基础资料查询','SYSTEM',GETDATE());

GO
 INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO,        
 FORMNAME, WEBURL, CREATOR, CREATEDATE,  PRIVOPTION, 
 ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY, 
 ExecutionMode,H5FUNCTIONKEY) 
VALUES  (N'B0405A', N'投诉提示总览', '39999.0', N'MWIP', '', 
         NULL, N'sMES', GETDATE(), '1', '0', 
         NULL, '', N'B0405A', '0','B0405A');
     
INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO,        
 FORMNAME, WEBURL, CREATOR, CREATEDATE,  PRIVOPTION, 
 ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY, 
 ExecutionMode,H5FUNCTIONKEY) 
VALUES  (N'B0406A', N'投诉提示编辑', '39999.0', N'MWIP', '', 
         NULL, N'sMES', GETDATE(), '1', '0', 
         NULL, '', N'B0406A', '0','B0406A');
     
     
 INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO,        
 FORMNAME, WEBURL, CREATOR, CREATEDATE,  PRIVOPTION, 
 ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY, 
 ExecutionMode,H5FUNCTIONKEY) 
VALUES  (N'B0407A', N'成品检验', '39999.0', N'MWIP', '', 
         NULL, N'sMES', GETDATE(), '1', '0', 
         NULL, '', N'B0407A', '0','B0407A');
     
 INSERT INTO TBLSYSFUNCTION (FUNCTIONNO, FUNCTIONNAME, FUNCTIONORDER, MODULENO,        
 FORMNAME, WEBURL, CREATOR, CREATEDATE,  PRIVOPTION, 
 ISSUEOPTION, ISSUETABLE, EXECUTIONFILE, FUNCTIONKEY, 
 ExecutionMode,H5FUNCTIONKEY) 
VALUES  (N'B0408A', N'成品检验记录', '39999.0', N'MWIP', '', 
         NULL, N'sMES', GETDATE(), '1', '0', 
         NULL, '', N'B0408A', '0','B0408A');
GO
INSERT INTO TBLSYSPAGENUMBERINFOBASIS(PAGEMODE,PAGESCRIPT,ACTIVE,DESCRIPTION,CREATOR,CREATEDATE)
VALUES('4_1',' Select  OPNo As page_no, OPName As page_name, Description As page_desc ,''1'' As favourite From  TBLOPBASIS A JOIN  TBLUSRGROUPPRIV C ON C.PRIVNO =A.OPNO JOIN TBLUSRUSERGROUP D ON C.GROUPNO=D.GROUPNO Where   IssueState = 2  {where} GROUP BY OPNo,OPName,Description',1,'质检过站权限查询','SYSTEM',GETDATE());
GO
alter TABLE TBLEQPEQUIPMENTBASIS add C_LEADPROCESS numeric(1,0) DEFAULT 0 NOT NULL
GO
alter TABLE tblReasonLog add COLOR int DEFAULT 0 NULL
GO
CREATE TABLE [dbo].[TBLCUSIntegrateSet] (
[Purpose] numeric(1) NOT NULL ,
[Workshop] nvarchar(100) NULL ,
[Database] nvarchar(300) NULL ,
[Account] nvarchar(100) NULL ,
[Password] nvarchar(50) NULL ,
[Datasheet] nvarchar(50) NULL ,
[HardwareID] nvarchar(20) NULL ,
[Equipmentno] nvarchar(20) NULL ,
[Opno] nvarchar(50) NULL 
)


GO
GO
CREATE TABLE [dbo].[TBLCUSCuttingMiddle] (
[Purpose] numeric(1) NOT NULL ,
[Workshop] nvarchar(100) NULL ,
[Database] nvarchar(100) NULL ,
[Account] nvarchar(100) NULL ,
[Password] nvarchar(50) NULL ,
[Datasheet] nvarchar(50) NULL ,
[HardwareID] nvarchar(20) NULL ,
[Equipmentno] nvarchar(20) NULL ,
[Opno] nvarchar(50) NULL 
)
GO
GO
INSERT INTO TBLSYSPARAMETER(PARAMETERTYPE,PARAMETERNO,PARAMETERVALUE,PARAMETERVISABLE) VALUES('SysInfo','SN2$SN3','SN2$SN3.btw',1);

INSERT INTO TBLSYSPARAMETER(PARAMETERTYPE,PARAMETERNO,PARAMETERVALUE,PARAMETERVISABLE) VALUES('SysInfo','SN2$SN3_2','SN2$SN3_2.btw',1);
GO
ALTER TABLE TBLWIPLOTBASIS ADD ISFINISHCHECK VARCHAR(2);
ALTER TABLE TBLPRDSUBOPCOLLECTION ADD AUTOPRINTSN_C VARCHAR(2);
GO
